#!/usr/bin/env bash

param(
    [String]$ReleaseName
)

if ([string]::IsNullOrEmpty($ReleaseName)) {
    $ReleaseName = git symbolic-ref HEAD
}

$BUILD_COMMIT = git rev-parse HEAD
$BAULK_BUILD_TIME = Get-Date -Format "dddd yyyy-MM-dd HH:mm:ss K"

$FileName = Join-Path $PSScriptRoot "include/baulkversion.h"

"// Do not edit, this file is generated by the script
#ifndef BAULK_BAULKVERSION_H
#define BAULK_BAULKVERSION_H

#define BAULK_RELEASE_NAME L`"$ReleaseName`"
#define BAULK_RELEASE_COMMIT L`"$BUILD_COMMIT`"
#define BAULK_BUILD_TIME L`"$BAULK_BUILD_TIME`"

#endif

" | Out-File -Encoding utf8 -FilePath $FileName

Write-Host "Gen baulkversion.h done
BAULK_RELEASE_NAME=$ReleaseName 
BAULK_RELEASE_COMMIT=$BUILD_COMMIT
BAULK_BUILD_TIME=$BAULK_BUILD_TIME"