///
#ifndef SSH_ASKPASS_BAULK_RESOURCE_H
#define SSH_ASKPASS_BAULK_RESOURCE_H

#define ICON_MAIN 256
#define IDM_ASKPASS_ABOUT 500
#define IDD_ASKPASS_WINDOW 1001
#define IDS_PROMPT_CONTENT 1002
#define IDE_ASKPASS_INPUT 1003
#define IDB_ASKPASS_CANCEL 1004
#define IDB_ASKPASS_OK 1005

#endif
