///
#ifndef BAULK_DOCK_BAULK_RESOURCE_H
#define BAULK_DOCK_BAULK_RESOURCE_H

#define ICON_MAIN 256
#define IDM_BAULK_DOCK_ABOUT 500
#define IDD_BAULK_DOCK_WINDOW 1001

#define IDC_BUTTON_STARTTASK 2101
#define IDC_BUTTON_STARTENV 2102
#define IDM_ENGINE_COMBOX 2103

#endif
